Added privacy policy to extension welcome page
mozilla-extensions/firefox-bridge pull request #107
Opened 2024-05-10 18:28 UTC by nipunshukla21

Added privacy policy and moved telemetry toggle to the bottom of the welcome page.

There were some issues with adding new lines to the welcome page within the same `data-locale` tag which seem to be preexisting. For now I've made the Privacy Policy three separate pararaphs.

![image](https://github.com/mozilla-extensions/firefox-bridge/assets/30131536/b0d4b002-cd40-4147-8d0c-31ab99674c50)

2024-05-13 23:12 UTC, bcolsson requested changes

2024-05-13 23:12 UTC, bcolsson commented on src/_locales/en/messages.json
>    "welcomePageTelemetryCheckbox": {
This needs a new ID since the text has changed.

2024-05-14 22:55 UTC, drubino-mozilla commented on src/_locales/en/messages.json
> +    "message": "The Firefox Bridge Extension allows you to open a web page in the browser of your choice. The <a>Mozilla Privacy Policy</a> describes how we handle information that we receive from yo
Change the "E" in "Extension" to a lowercase "e"

2024-05-14 22:56 UTC, drubino-mozilla commented on src/_locales/en/messages.json
> +    "message": "Interaction data. Mozilla receives information about your interaction with Firefox Bridge across all instances of Firefox Bridge on your device, including (1) Event Data and Metrics d
Remove the comma between "device" and "operating system"

2024-05-15 05:33 UTC, flodolo commented on src/_locales/en/messages.json
> +    "message": "Interaction data. Mozilla receives information about your interaction with Firefox Bridge across all instances of Firefox Bridge on your device, including (1) Event Data and Metrics d
```suggestion
    "message": "Interaction data. Mozilla receives information about your interaction with Firefox Bridge across all instances of Firefox Bridge on your device, including (1) Event Data and Metrics data, such as when and how many pages you open in a new browser (though not what those pages are), (2) Interactions with Firefox Bridge’s menus and icons, and (3) Length of time you use the extension. We also receive your device operating system, version, and language preference, etc."
```

Drop double-spacing.

2024-05-15 05:33 UTC, flodolo commented on src/_locales/en/messages.json
> +    "message": "Here are the key things you should know about how the Firefox Bridge Extension handles your data:"
```suggestion
    "message": "Here are the key things you should know about how the Firefox Bridge extension handles your data:"
```
"Extension" here, but "extension" in the previous string. Which one is correct? I assume extension, given David's comment.

2024-05-15 05:33 UTC, flodolo commented on src/shared/pages/welcomePage/localization.js
> +    welcomePagePrivacyPolicyIntro: "https://www.mozilla.org/en-US/privacy/",
```suggestion
    welcomePagePrivacyPolicyIntro: "https://www.mozilla.org/privacy/",
```

For mozilla.org, never link to a specific language, let the website deal with the language negotiation.

2024-05-15 16:43 UTC, bcolsson approved these changes

2024-05-15 16:49 UTC, merged